### ISSUE TITLE
Limit maximum toasts

### ISSUE THREAD

**Issue by phiphi282** [freitagsrunde/k4ever-frontend#8]
There should be a maximum amount of toasts that will be shown as once.

Screenshot:
![screenshot_2019-03-01 k4frontend](https://user-images.githubusercontent.com/32705812/53647603-349f3a00-3c3e-11e9-8443-ee5a7ece64bf.png)

This example isn't as relevant since I use the application in an unintended way but the error might become more important in the future.

**Comment by zergar** [comment]
This is not possible with `vue-toasted` according to https://github.com/shakee93/vue-toasted/issues/64. It would be possible to reduce the display duration for toasts from `3000ms` to e.g. `1500ms` as a workaround but I'd argue that an user usually does not click any button more than 5 times per second unless he wants to do something malicious.
